# Generated by Django 6.1.1 on 2026-09-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_host_room_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rounds',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
