# Generated by Django 6.1.1 on 2026-09-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_room_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='imposter_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
