# Generated by Django 6.1.1 on 2026-09-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_room_imposter_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
