# Generated by Django 6.1.1 on 2026-09-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_room_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('none', 'None'), ('standard', 'Standard'), ('imposter', 'Imposter')], default='none', max_length=10),
        ),
    ]
