# Generated by Django 6.1.1 on 2026-09-08 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_room', to='game.room'),
        ),
    ]
