# Generated by Django 6.1.1 on 2026-09-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_user_current_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_room_player_order_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
