# Generated by Django 6.1.1 on 2026-09-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_user_current_room_player_order_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_room_player_order_index',
        ),
    ]
