# Generated by Django 6.1.1 on 2026-09-16 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_user_current_room_player_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='first_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_first_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
