# Generated by Django 6.1.1 on 2026-09-17 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_room_first_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_current_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
