# Generated by Django 6.1.1 on 2026-09-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_room_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='selected_category',
            field=models.CharField(choices=[('none', 'None'), ('point', 'Point'), ('hands', 'Hands'), ('fingers', 'Fingers'), ('words', 'Words')], default='none', max_length=10),
        ),
    ]
