# Generated by Django 6.1.1 on 2026-09-21 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_room_selected_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='card_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='first_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_first_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
