# Generated by Django 6.1.1 on 2026-09-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_room_card_index_alter_room_first_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='selected_category',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('point', 'Point'), ('hands', 'Hands'), ('fingers', 'Fingers'), ('words', 'Words')], default='none', max_length=10, null=True),
        ),
    ]
