# Generated by Django 6.1.1 on 2026-09-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_room_selected_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
