# Generated by Django 6.1.1 on 2026-09-24 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_user_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
