# Generated by Django 6.1.1 on 2026-09-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_user_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='voting',
            field=models.BooleanField(default=False),
        ),
    ]
